### ISSUE TITLE
Create a Mapcrafter Cronjob

### ISSUE THREAD

**Issue by MatSeifert** [MatSeifert/VMPHomepage#2]
Um die Mincraft Servermap up to date zu halten, brauchen wir einen Cronjob, der die Karte automtaisch in einem festgelegten Intervall updatet. Je nachdem, wie aufwändig die Berechnung der Map ist, kann das Intervall größer oder kleiner gewählt werden (täglich, alle 3 Tage, einmal die Woche). Auf jeden Fall sollte das ganze nachts oder am frühen morgen laufen, um Performance Flaschenhälse zu meiden.

Zudem müssten wir vorher noch diskutieren, welche Optionen wir für die Map Generierung festlegen.

**Comment by LehmRob** [comment]
Wo soll den die Map hinerstellt werden? `content/mapcrafter/build`. Oder habt ihr da andere Vorstellungen?

**Comment by FireLizard** [comment]
Jup, würde ich machen, solang sich an der Verzeichnisstruktur der Website nichts ändert. Der mapcrafter erstellt sozusagen eine eigenständige HTML-Seite und nutzt die unter `content/mapcrafter/template` eingestellten Templates.
Auf dem Server unter `~/.mapcrafter/conf/` findet ihr die [Konifgurationsdatei](http://docs.mapcrafter.org/builds/stable/configuration.html).

**Comment by LehmRob** [comment]
Der Cronjob ist registriert. Im Wiki habe ich mal eine kurze Erklärung dazu verfasst.

**Comment by FireLizard** [comment]
Danke! Sieht gut aus :+1:
